# Generated by Django 3.1.2 on 2020-10-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uuid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('url', models.CharField(max_length=256)),
                ('repo_url', models.CharField(max_length=256)),
                ('json_blob', models.TextField()),
            ],
        ),
    ]
