# Generated by Django 3.1.2 on 2020-10-26 02:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=256)),
                ('started_at', models.DateTimeField(default=datetime.datetime(2020, 10, 25, 20, 9, 47, 799408))),
                ('json_blob', models.TextField()),
                ('total_commits', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repos', to='Users.users')),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('uuid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('contributions', models.IntegerField()),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='Repos.repo')),
            ],
        ),
    ]
