# Generated by Django 3.1.2 on 2020-10-26 02:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='open_issues',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='repo',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 25, 20, 17, 21, 470602)),
        ),
    ]
